import test from 'node:test';import assert from 'node:assert/strict';
import {DeterministicIntentResolver,discoverOperations,stewardIdentity,organisationalLearning,STEWARD_ACTOR_ID} from '../src/index.mjs';

const context={capabilities:[{id:'customer_support',name:'Customer Support'}],resources:[{id:'production_environment',name:'Production Environment'},{id:'old_environment',name:'Old Environment'}]};
test('registered operations expose shared machine-readable governance metadata',()=>{const plan=discoverOperations().find(item=>item.id==='generate_plan');assert.equal(plan.runtimeOperation,'generatePlan');assert.deepEqual(new Set(plan.interfaces),new Set(['ui','lily','api','cli','controller']));assert.equal(plan.mutation,false);assert.deepEqual(plan.permissions,['plan_company'])});
test('natural language resolves to structured registered operations',async()=>{const result=await new DeterministicIntentResolver().resolve('Sort out customer support.',context,discoverOperations({interface:'lily'}));assert.equal(result.status,'resolved');assert.equal(result.target,'customer_support');assert.deepEqual(result.candidateOperations,['get_capability','resolve_capability','generate_plan','present_plan'])});
test('ambiguous destructive intent requires clarification before planning',async()=>{const result=await new DeterministicIntentResolver().resolve('Delete the old environment.',{...context,resources:[{id:'old_environment_eu'},{id:'old_environment_us'}]},discoverOperations());assert.equal(result.status,'clarification_required');assert.equal(result.requiresClarification,true)});
test('request execution identifies approval-governed apply rather than executing',async()=>{const result=await new DeterministicIntentResolver().resolve('Go ahead and fix it.',context,discoverOperations());assert.equal(result.requiresApproval,true);assert.ok(result.candidateOperations.includes('apply_plan'))});
test('asking how to fix requests resolution and planning, not apply',async()=>{const result=await new DeterministicIntentResolver().resolve('How would you fix customer support?',context,discoverOperations({interface:'lily'}));assert.equal(result.intent,'realise_capability');assert.equal(result.requiresApproval,undefined);assert.ok(result.candidateOperations.includes('resolve_capability'));assert.equal(result.candidateOperations.includes('apply_plan'),false)});
test('Lily presentation name does not change operational identity',()=>{assert.equal(stewardIdentity({displayName:'Rose'}).actorId,STEWARD_ACTOR_ID);assert.equal(stewardIdentity({displayName:'Rose'}).displayName,'Rose')});
test('organisational learning retains provenance and is candidate by default',()=>{const item=organisationalLearning({id:'learning_1',statement:'Weekly summaries are preferred',source:'customer_research',learnedAt:'2026-01-01T00:00:00Z',evidenceReferences:['evidence:1']});assert.equal(item.validationStatus,'candidate');assert.deepEqual(item.evidenceReferences,['evidence:1'])});
test('a resource name resolves before operation selection',async()=>{const result=await new DeterministicIntentResolver().resolve('Gmail',{...context,resources:[{id:'gmail_connector',name:'Gmail Connector',category:'connector',realises:['customer_support']}]},discoverOperations({interface:'lily'}));assert.equal(result.status,'resolved');assert.equal(result.intent,'inspect_entity');assert.equal(result.target,'gmail_connector');assert.ok(result.candidateOperations.includes('get_resource'))});
test('pronouns resolve from structured interaction context',async()=>{const resolver=new DeterministicIntentResolver(),available=discoverOperations({interface:'lily'}),company={...context,resources:[{id:'gmail_connector',name:'Gmail Connector',category:'connector'}]};const result=await resolver.resolve('What does this do?',company,available,{currentRoute:'/infrastructure',selectedResource:'gmail_connector'});assert.equal(result.target,'gmail_connector');assert.equal(result.intent,'inspect_entity')});
test('ambiguous entity names require clarification',async()=>{const result=await new DeterministicIntentResolver().resolve('Gmail',{...context,resources:[{id:'gmail_sales',name:'Gmail Connector'},{id:'gmail_support',name:'Gmail Connector'}]},discoverOperations({interface:'lily'}));assert.equal(result.status,'clarification_required');assert.equal(result.entities.length,2)});
test('contextual resource removal resolves to inspection and planning, never provider execution',async()=>{const company={...context,resources:[{id:'gmail_connector',name:'Gmail Connector',category:'connector',realises:['customer_support']}]};const result=await new DeterministicIntentResolver().resolve('Remove it',company,discoverOperations({interface:'lily'}),{selectedResource:'gmail_connector'});assert.equal(result.intent,'change_resource');assert.equal(result.requiresApproval,true);assert.deepEqual(result.candidateOperations,['get_resource','generate_plan'])});
