import test from 'node:test';import assert from 'node:assert/strict';
import {DeterministicIntentResolver,discoverOperations,stewardIdentity,organisationalLearning,STEWARD_ACTOR_ID} from '../src/index.mjs';

const context={capabilities:[{id:'customer_support',name:'Customer Support'}],resources:[{id:'production_environment',name:'Production Environment'},{id:'old_environment',name:'Old Environment'}]};
test('registered operations expose shared machine-readable governance metadata',()=>{const plan=discoverOperations().find(item=>item.id==='generate_plan');assert.equal(plan.runtimeOperation,'generatePlan');assert.deepEqual(new Set(plan.interfaces),new Set(['ui','lily','api','cli','controller']));assert.equal(plan.mutation,false);assert.deepEqual(plan.permissions,['plan_company'])});
test('natural language resolves to structured registered operations',async()=>{const result=await new DeterministicIntentResolver().resolve('Sort out customer support.',context,discoverOperations({interface:'lily'}));assert.equal(result.status,'resolved');assert.equal(result.target,'customer_support');assert.deepEqual(result.candidateOperations,['get_capability','generate_plan','present_plan'])});
test('ambiguous destructive intent requires clarification before planning',async()=>{const result=await new DeterministicIntentResolver().resolve('Delete the old environment.',{...context,resources:[{id:'old_environment_eu'},{id:'old_environment_us'}]},discoverOperations());assert.equal(result.status,'clarification_required');assert.equal(result.requiresClarification,true)});
test('request execution identifies approval-governed apply rather than executing',async()=>{const result=await new DeterministicIntentResolver().resolve('Go ahead and fix it.',context,discoverOperations());assert.equal(result.requiresApproval,true);assert.ok(result.candidateOperations.includes('apply_plan'))});
test('Lily presentation name does not change operational identity',()=>{assert.equal(stewardIdentity({displayName:'Rose'}).actorId,STEWARD_ACTOR_ID);assert.equal(stewardIdentity({displayName:'Rose'}).displayName,'Rose')});
test('organisational learning retains provenance and is candidate by default',()=>{const item=organisationalLearning({id:'learning_1',statement:'Weekly summaries are preferred',source:'customer_research',learnedAt:'2026-01-01T00:00:00Z',evidenceReferences:['evidence:1']});assert.equal(item.validationStatus,'candidate');assert.deepEqual(item.evidenceReferences,['evidence:1'])});
