import test from 'node:test';import assert from 'node:assert/strict';
import {CapabilityResolver,evaluateCapabilityCoverage,realisationAttempt,attentionItems} from '../src/index.mjs';
import {OmniSeedRuntime} from '../src/runtime.mjs';

const capability={id:'customer_support',name:'Customer Support',required:true,requirements:[{capability:'receive_request',required:true},{capability:'understand_request',required:true},{capability:'approve_large_refund',required:true,humanAuthority:{reason:'Refunds above £500 require delegated authority.'}}]};
const resources=[{id:'support_agent',category:'agent',realises:['customer_support'],offers:['understand_request'],skills:['classify_request'],connectors:['gmail']},{id:'gmail',category:'connector',realises:['customer_support'],offers:['receive_request']}];
test('coverage is calculated from active offerings and keeps human authority explicit',()=>{const result=evaluateCapabilityCoverage(capability,resources,{resources:{support_agent:{status:'active'},gmail:{status:'active'}}});assert.equal(result.state,'partial');assert.deepEqual(result.coverage,{required:3,covered:2,missing:['approve_large_refund']});assert.equal(result.humanDependencies[0].requirement,'approve_large_refund');assert.equal(result.autonomy,'human_dependent')});
test('provider offerings are selected by strategy without semantic execution',()=>{const result=new CapabilityResolver().resolve({capability,resources,deployment:{resources:{}},providerOfferings:[{id:'human',category:'person',offers:['approve_large_refund']},{id:'local-agent',category:'agent',offers:['receive_request','understand_request']}],strategy:{realisationPreference:['agent','workflow','person']}});assert.equal(result.recommendedRealisation.id,'local-agent');assert.deepEqual(result.recommendedRealisation.covers,['receive_request','understand_request'])});
test('attempts and attention expose bounded lifecycle truth',()=>{assert.equal(realisationAttempt({capabilityId:'customer_support',number:1,result:'retryable'}).terminal,false);assert.equal(realisationAttempt({capabilityId:'customer_support',number:2,result:'blocked'}).terminal,true);assert.equal(attentionItems({capabilities:[{...capability,state:'partial',missingRequirements:[{id:'approve_large_refund'}]}]})[0].reason,'approve_large_refund')});
test('runtime registry resolves capability and governed accepted gap',async()=>{const definition={omniform:'0.1',company:{id:'acme',name:'Acme',purpose:'Support customers',capabilities:[capability],resources,providerOfferings:[],strategy:{realisationPreference:['agent','person']}}};const runtime=new OmniSeedRuntime({definition,deployment:{resources:{support_agent:{status:'active'},gmail:{status:'active'}}}});assert.equal(runtime.getCapability({id:'customer_support'}).state,'partial');assert.equal((await runtime.resolveIntent({utterance:'I need customer support'})).intent,'realise_capability');const accepted=await runtime.executeOperation({id:'accept_capability_gap',input:{capabilityId:'customer_support',reason:'Launch scope',authorization:{actorId:'founder',permissions:['govern_company']}},authorization:{permissions:['govern_company'],approved:true}});assert.equal(accepted.capability.state,'gap_accepted')});
