import fs from 'node:fs';

export const CORE_OPERATION_CATALOG=Object.freeze(JSON.parse(fs.readFileSync(new URL('../../../generated/omniform-core.operations.json',import.meta.url),'utf8')));

export function compileOmniform(catalog,{handlers={},bindings={}}={}){
 const capabilityIds=new Set((catalog?.capabilities||[]).map(item=>item.id));const seen=new Set();const errors=[];
 const operations=(catalog?.operations||[]).map(contract=>{if(seen.has(contract.id))errors.push(`duplicate operation ${contract.id}`);seen.add(contract.id);if(!capabilityIds.has(contract.capability))errors.push(`operation ${contract.id} references missing capability ${contract.capability}`);const implementation=handlers[contract.id];const binding=bindings[contract.id];let unavailableReason=null;if(!implementation)unavailableReason='missing implementation';else if(binding?.available===false)unavailableReason=binding.reason||'missing provider';return {...structuredClone(contract),available:!unavailableReason,unavailableReason,implementedBy:implementation?.implementedBy||null,runtimeOperation:implementation?.runtimeOperation||null}});
 for(const id of Object.keys(handlers))if(!seen.has(id))errors.push(`implementation ${id} has no Omniform operation definition`);
 if(errors.length)throw new Error(`Omniform compilation failed: ${errors.join('; ')}`);
 const byId=Object.fromEntries(operations.map(item=>[item.id,item]));
 return {source:{kind:'omniform-operation-catalog',version:catalog.catalogVersion},capabilities:structuredClone(catalog.capabilities),operations,schemas:Object.fromEntries(operations.map(item=>[item.id,{input:item.input,output:item.output}])),get(id){return byId[id]||null},list({interface:surface}={}){return structuredClone(surface?operations.filter(item=>item.interfaces.includes(surface)):operations)},async execute(id,input={},context={}){const operation=byId[id];if(!operation)throw coded(`Unknown Omniform operation: ${id}`,404);if(!operation.available)throw coded(`Operation ${id} unavailable: ${operation.unavailableReason}`,409);const inputErrors=validateSchema(operation.input,input);if(inputErrors.length)throw detailed(`Invalid input for ${id}`,400,inputErrors);const permissions=context.authorization?.permissions||[];const missing=operation.permissions.filter(permission=>!permissions.includes(permission));if(missing.length)throw coded(`${missing.join(', ')} authorization required`,403);if(operation.mutation&&operation.approval.mode==='required'&&!context.authorization?.approved)throw coded(`Approval required for ${id}`,403);const result=await handlers[id](input,context);const outputErrors=validateSchema(operation.output,result);if(outputErrors.length)throw detailed(`Handler output violates ${id}`,500,outputErrors);return result}};
}

export function operationToolDefinitions(registry){return registry.list({interface:'agent'}).map(item=>({name:item.id,description:item.description,inputSchema:item.input,outputSchema:item.output,metadata:{version:item.version,mutation:item.mutation,approval:item.approval,risk:item.risk,permissions:item.permissions,available:item.available,unavailableReason:item.unavailableReason}}))}
export function operationIndex(registry){return {source:registry.source,operations:registry.list().map(({input,output,...item})=>({...item,inputSchema:input,outputSchema:output}))}}
export function validateSchema(schema,value,path='$'){const errors=[];if(!schema)return errors;const types=Array.isArray(schema.type)?schema.type:[schema.type];if(types[0]&&!types.some(type=>matches(type,value)))return [{path,message:`must be ${types.join(' or ')}`}];if(value&&typeof value==='object'&&!Array.isArray(value)){for(const key of schema.required||[])if(!(key in value))errors.push({path:`${path}.${key}`,message:'is required'});if(schema.additionalProperties===false)for(const key of Object.keys(value))if(!schema.properties?.[key])errors.push({path:`${path}.${key}`,message:'is not allowed'});for(const [key,child] of Object.entries(schema.properties||{}))if(key in value)errors.push(...validateSchema(child,value[key],`${path}.${key}`))}if(Array.isArray(value)&&schema.items)for(let index=0;index<value.length;index++)errors.push(...validateSchema(schema.items,value[index],`${path}[${index}]`));if(typeof value==='string'&&schema.pattern&&!new RegExp(schema.pattern).test(value))errors.push({path,message:'does not match pattern'});return errors}
function matches(type,value){return type==='null'?value===null:type==='array'?Array.isArray(value):type==='object'?Boolean(value)&&typeof value==='object'&&!Array.isArray(value):typeof value===type}
function coded(message,statusCode){return Object.assign(new Error(message),{statusCode})}function detailed(message,statusCode,details){return Object.assign(new Error(message),{statusCode,details})}
