import crypto from 'node:crypto';import {validateDefinition} from './index.mjs';
const statuses=['proposed','accepted','rejected','edited'];export const FOUNDING_STATUSES=statuses;
const item=(id,name,rationale,confidence=.9)=>({id,name,status:'proposed',rationale,confidence,source:'mock-founding-designer'});
export class MockFoundingDesigner {
  async analyseIntent({text}){if(!text?.trim())throw new Error('Founder intent is required');return {company:{id:'construction_cashflow',name:'Construction Cashflow',purpose:'Help small construction businesses manage invoices and late payments',status:'proposed',rationale:'The intent identifies a clear customer, problem, and SaaS product direction.',confidence:.95,source:'mock-founding-designer'},outcomes:[item('invoices_managed','Customers can create and track invoices','Invoice creation and tracking is the core customer result.'),item('overdue_identified','Customers can identify overdue payments','Late-payment work begins with reliable identification.'),item('late_payments_pursued','Customers can pursue late payments effectively','The stated problem includes chasing overdue invoices.'),item('customers_supported','The company can acquire and support customers','A SaaS company requires repeatable acquisition and support.'),item('service_monetised','The company can charge for the service','Commercial operation requires a charging outcome.')],capabilities:[item('customer_discovery','Customer Discovery','The company must continuously understand construction-company needs.'),item('product_delivery','Product Delivery','The SaaS product must be built and operated.'),item('invoice_management','Invoice Management','Customers need to create and track invoices.'),item('payment_tracking','Payment Tracking','The product must identify overdue payments.'),item('customer_acquisition','Customer Acquisition','The business needs a repeatable way to find and convert construction companies.'),item('billing','Billing','The company needs to charge for its service.'),item('customer_support','Customer Support','Customers need help using a financial workflow product.'),item('financial_operations','Financial Operations','The company must manage its own financial obligations.')],policies:[],observations:[],resourceSuggestions:[{...item('invoice_implementation','Invoice-management realisation','Could be realised by software, workflow, people, agents, or a combination.',.7),capabilityId:'invoice_management',options:['software system','workflow','human','AI agent','external partner','combination']}],assumptions:[{id:'small_construction_focus',statement:'Initial customers are small construction businesses',confidence:.9}],openQuestions:[{id:'charging_model',question:'How will customers be charged?',options:['subscription','transaction fee','usage-based','other'],required:false}],version:1};}
  async refineProposal(proposal,instruction){return {...structuredClone(proposal),version:proposal.version+1,advisoryNote:`Refinement requested: ${instruction}`}}
}
export function validateFoundingProposal(proposal){const errors=[];if(!proposal?.company?.id||!proposal.company.name||!proposal.company.purpose)errors.push('company is incomplete');for(const group of ['outcomes','capabilities','policies','observations','resourceSuggestions'])for(const candidate of proposal?.[group]||[]){if(!candidate.id||!statuses.includes(candidate.status)||typeof candidate.rationale!=='string'||typeof candidate.confidence!=='number'||!candidate.source)errors.push(`invalid ${group} item ${candidate.id||'unknown'}`)}return {valid:errors.length===0,errors}}
export function proposalToOmniform(proposal){const accepted=group=>(proposal[group]||[]).filter(candidate=>['accepted','edited'].includes(candidate.status));return {omniform:'0.1',company:{id:proposal.company.id,name:proposal.company.name,purpose:proposal.company.purpose,outcomes:accepted('outcomes').map(({id,name})=>({id,description:name})),capabilities:accepted('capabilities').map(({id,name})=>({id,name,required:true})),resources:[],policies:accepted('policies').map(({id,name})=>({id,rule:name})),observations:accepted('observations').map(({id,type,capability,condition})=>({id,type,capability,condition}))}}}
export class FoundingService {
  constructor({designer=new MockFoundingDesigner(),clock=()=>new Date().toISOString()}={}){this.designer=designer;this.clock=clock;this.sessions=new Map()}
  event(session,type,data={}){session.events.push({specversion:'1.0',type,source:'omniseed/founding',time:this.clock(),data})}
  startFoundingSession({actorId}){const id=`founding_${crypto.randomUUID()}`;const session={id,status:'intent',actorId,proposal:null,events:[]};this.sessions.set(id,session);this.event(session,'founding.started',{sessionId:id,actorId});return structuredClone(session)}
  async submitFounderIntent({sessionId,intent}){const session=this.require(sessionId);this.event(session,'founding.intent.submitted',{sessionId,intentLength:intent.length});session.proposal=await this.designer.analyseIntent({text:intent});session.status='proposed';this.event(session,'founding.proposal.generated',{sessionId,version:session.proposal.version});return structuredClone(session.proposal)}
  getFoundingDraft({sessionId}){return structuredClone(this.require(sessionId))}
  async refineFoundingDraft({sessionId,instruction}){const session=this.require(sessionId);session.proposal=await this.designer.refineProposal(session.proposal,instruction);this.event(session,'founding.proposal.refined',{sessionId,version:session.proposal.version});return structuredClone(session.proposal)}
  updateDraftItem({sessionId,section,itemId,status,name}){const session=this.require(sessionId),candidate=session.proposal?.[section]?.find(item=>item.id===itemId);if(!candidate)throw new Error('Draft item not found');if(!statuses.includes(status))throw new Error('Invalid draft status');candidate.status=status;if(name){candidate.name=name;candidate.status='edited'}session.status='reviewed';session.proposal.version++;this.event(session,status==='accepted'?'founding.item.accepted':status==='rejected'?'founding.item.rejected':'founding.proposal.refined',{sessionId,section,itemId});return structuredClone(candidate)}
  addDraftItem({sessionId,section='capabilities',item}){const session=this.require(sessionId);if(!['outcomes','capabilities','policies','observations','resourceSuggestions'].includes(section))throw new Error('Invalid draft section');const candidate={id:item.id,name:item.name,status:'edited',rationale:item.rationale||'Added by the founder.',confidence:1,source:'founder'};session.proposal[section].push(candidate);session.proposal.version++;this.event(session,'founding.proposal.refined',{sessionId,section,itemId:candidate.id,added:true});return structuredClone(candidate)}
  explainFoundingItem({sessionId,section,itemId}){const session=this.require(sessionId),candidate=session.proposal?.[section]?.find(item=>item.id===itemId);if(!candidate)throw new Error('Draft item not found');return {id:candidate.id,name:candidate.name,rationale:candidate.rationale,confidence:candidate.confidence,source:candidate.source}}
  validateFoundingDraft({sessionId}){const session=this.require(sessionId),proposalValidation=validateFoundingProposal(session.proposal);if(!proposalValidation.valid)return proposalValidation;const definition=proposalToOmniform(session.proposal),definitionValidation=validateDefinition(definition),errors=[...definitionValidation.errors];if(!definition.company.capabilities.length)errors.push({path:'/company/capabilities',message:'accept or add at least one capability before founding'});return {valid:errors.length===0,errors,definition}}
  require(id){const session=this.sessions.get(id);if(!session)throw new Error('Founding session not found');return session}
}
