import fs from 'node:fs';
import {OmniSeedHost} from '../../core/src/host.mjs';
import {HostedKeyValueClient,HostedDefinitionStore,HostedStateStore,HostedRuntimeMetadataStore} from '../../core/src/stores.mjs';

const ownerPermissions=['read_company','plan_company','approve_plan','apply_plan','govern_company','commit_company'];
const ownerOnly=new Set(['generatePlan','cancelPlan','applyPlan','acceptCapabilityGap','startFoundingSession','submitFounderIntent','refineFoundingDraft','acceptDraftItem','rejectDraftItem','updateDraftItem','addDraftItem','commitFoundingDraft','loadCompany','generate_plan','apply_plan','accept_capability_gap']);

export function createHostedRuntime({companyId=process.env.OMNISEED_COMPANY_ID||'acme',client=new HostedKeyValueClient(),definition=read('company.json'),state=read('deployment-state.json')}={}){const definitionStore=new HostedDefinitionStore(client),stateStore=new HostedStateStore(client),metadataStore=new HostedRuntimeMetadataStore(client);return OmniSeedHost.open({companyId,definitionStore,stateStore,metadataStore,bootstrapDefinition:definition,bootstrapState:state})}

export async function handleHostedRuntimeRequest(request,options={}) {const url=new URL(request.url),match=url.pathname.match(/^\/api\/operations\/([A-Za-z][A-Za-z0-9_]+)$/);if(request.method==='GET'&&url.pathname==='/api/health')return json({status:'ok',runtime:'omniseed',mode:'live',persistence:'hosted'});if(!match||request.method!=='POST')return json({ok:false,error:{message:'not_found'}},404);try{const body=await request.json().catch(()=>({})),operation=match[1],owner=authenticate(request,options.ownerToken||process.env.OMNISEED_OWNER_TOKEN);if(ownerOnly.has(operation)&&!owner)return json({ok:false,error:{message:'Owner authorization required',code:'read_only_access'}},403);const host=await createHostedRuntime(options),authorization=owner?{actorId:'hosted_owner',permissions:ownerPermissions,approved:Boolean(body.authorization?.approved)}:{actorId:'public_visitor',permissions:['read_company']};let input=body.input||body;if(owner){if(['applyPlan','cancelPlan','acceptCapabilityGap','commitFoundingDraft'].includes(operation))input={...input,authorization};if(operation==='apply_plan')input={...input,authorization}}let result=operation.includes('_')?await host.invoke('executeOperation',{id:operation,input,authorization}):await host.invoke(operation,input);if(operation==='getRuntimeStatus')result={...result,access:owner?'owner':'read-only'};return json({ok:true,result,access:owner?'owner':'read-only'})}catch(error){return json({ok:false,error:{message:error.message,details:error.details}},error.statusCode||500)}}

function authenticate(request,expected){if(!expected)return false;const bearer=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');const cookie=request.headers.get('cookie')?.split(';').map(item=>item.trim().split('=')).find(([name])=>name==='omniseed_owner')?.[1];return Boolean((bearer||cookie)&&timingSafe(bearer||cookie,expected))}
function timingSafe(value,expected){if(value.length!==expected.length)return false;let result=0;for(let index=0;index<value.length;index++)result|=value.charCodeAt(index)^expected.charCodeAt(index);return result===0}
function read(name){return JSON.parse(fs.readFileSync(new URL(`../../../examples/hosted/${name}`,import.meta.url),'utf8'))}
function json(value,status=200){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json','cache-control':'no-store'}})}
