import {assertProvider,evidenceReference} from '../../packages/provider-sdk/src/index.mjs';

const TYPES=['vercel_project','vercel_deployment','vercel_domain'];
function config(resource){if(!TYPES.includes(resource?.type))throw new Error(`Vercel provider supports ${TYPES.join(', ')}`);const value=resource.provider?.vercel;if(!value?.name)throw new Error('provider.vercel.name is required');return value}

export function createVercelProvider({token,teamId,fetch:request=globalThis.fetch,apiUrl='https://api.vercel.com',clock=()=>new Date().toISOString()}={}){
 if(typeof request!=='function')throw new Error('Vercel provider requires fetch');
 async function call(path,options={}){const separator=path.includes('?')?'&':'?';const target=`${apiUrl}${path}${teamId?`${separator}teamId=${encodeURIComponent(teamId)}`:''}`;const response=await request(target,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...options.headers}});if(!response.ok)throw Object.assign(new Error(`Vercel API ${options.method||'GET'} ${path} failed (${response.status})`),{statusCode:response.status});return response.status===204?null:response.json()}
 return assertProvider({
  async validate(resource){try{config(resource);return {valid:true,errors:[]}}catch(error){return {valid:false,errors:[{message:error.message}]}}},
  async plan(change){const value=config(change.resource);return {provider:'vercel',action:change.action,resource:change.resource.id,externalType:change.resource.type,summary:`${change.action} ${change.resource.type} ${value.name}`,risk:change.resource.type==='vercel_domain'?'medium':'low',requiresAuthorization:true}},
  async apply(change){if(change.action!=='create')throw new Error(`Vercel provider does not yet apply ${change.action}`);const value=config(change.resource);if(change.resource.type==='vercel_project'){const item=await call('/v10/projects',{method:'POST',body:JSON.stringify({name:value.name,framework:value.framework})});return {providerId:`vercel:project:${item.id}`,status:'active',external:{id:item.id,name:item.name}}}if(change.resource.type==='vercel_deployment'){const item=await call('/v13/deployments',{method:'POST',body:JSON.stringify({name:value.name,project:value.project,gitSource:value.gitSource,target:value.target})});return {providerId:`vercel:deployment:${item.id}`,status:item.readyState==='READY'?'active':'pending',external:{id:item.id,url:item.url,readyState:item.readyState}}}const item=await call(`/v10/projects/${encodeURIComponent(value.project)}/domains`,{method:'POST',body:JSON.stringify({name:value.name})});return {providerId:`vercel:domain:${item.name}`,status:item.verified?'active':'pending',external:{name:item.name,verified:Boolean(item.verified)}}},
  async observe(resource,state={}){const value=config(resource);let item,path;if(resource.type==='vercel_project')path=`/v9/projects/${encodeURIComponent(value.projectId||value.name)}`;else if(resource.type==='vercel_deployment')path=`/v13/deployments/${encodeURIComponent(value.deploymentId||state.providerId?.split(':').at(-1)||value.name)}`;else path=`/v6/domains/${encodeURIComponent(value.name)}`;item=await call(path);const id=String(item.id||item.name);const status=item.readyState?(item.readyState==='READY'?'active':'degraded'):(item.verified===false?'degraded':'active');return {resource:resource.id,status,external:{id,name:item.name,url:item.url,readyState:item.readyState,verified:item.verified},evidence:[evidenceReference({provider:'vercel',type:resource.type,id,observedAt:clock(),attributes:{status,url:item.url,verified:item.verified}})]}}
 });
}
export default createVercelProvider;
